#!/bin/sh

. "$2"

url="https://zlib.net/zlib-1.3.1.tar.gz"

configure() {
    ./configure --prefix="/usr"
}

build() {
    make -j$(nproc)
}

install() {
    make DESTDIR="$1" install -j$(nproc)
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
