#!/bin/sh

. "$2"

url="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.18.3.tar.xz"

configure() {
    make defconfig
    rm -rf .config
    cp -rf "$script_dir/ferris_linux_config" ".config"
}

build() {
    make -j$(nproc)
}

install() {
    make INSTALL_PATH="$1/boot" install -j$(nproc)
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
